on:
  push

jobs:
  update-dyno-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          cache: 'pip'
          python-version: '3.13'
          allow-prereleases: true
          check-latest: true
      - run: python -m pip install -r requirements.txt
      - id: branch-name
        run: echo "value=$(ozi -v)" >> $GITHUB_OUTPUT
      - run: git checkout -b "$BRANCH_NAME"
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.value }}
      - run: |
          ozi-new -n dyno \
          -a "OZI Project" -e "help@oziproject.dev" \
          -l "MIT" --license-expression "MIT0" \
          -s "OZI Github actions test dyno" \
