on:
  push:
    branches: main
    paths:
      - 'requirements.txt'
      - 'templates/**'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-dyno-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          cache: 'pip'
          python-version: '3.13'
          allow-prereleases: true
          check-latest: true
      - run: python -m pip install -r requirements.txt
      - id: branch-name
        run: echo "value=$(ozi -v)" >> $GITHUB_OUTPUT
      - run: |
          git checkout -b "$BRANCH_NAME"
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.value }}
      - run: |
          ozi-new project \
          --testpypi \
          -n dyno \
          -a "OZI Project" \
          -e "help@oziproject.dev" \
          -l "MIT" \
          --license-expression "MIT-0" \
          -s "OZI Github actions test dyno" \
          --allow-file templates \
          --allow-file .git \
          --allow-file .pre-commit-config.yaml \
          --allow-file .github \
          --allow-file README.md \
          --allow-file requirements.txt \
          --no-enable-create-pull-request \
          --update-wrapfile
      - id: add-test-dyno
        run: echo "value=$(ozi-fix test --add test_dyno.py)" >> $GITHUB_OUTPUT
      - run: |
          echo '### ``ozi-fix test --add test_dyno.py``' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.add-test-dyno.outputs.value }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - run: |
          echo '### ``black --diff -S .``' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          black --diff -S . >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - run: ozi-fix missing --update-wrapfile
      - run: black -S .
      - run: meson rewrite command '${{ steps.add-test-dyno.outputs.value }}'
      - run: |
          git config --global user.email "help@oziproject.dev"
          git config --global user.name "OZI Project"
          git add -A
          git commit -m "OZI $BRANCH_NAME"
          git push -u origin "$BRANCH_NAME"
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.value }}
