
# Part of dyno.
# See LICENSE.txt in the project root for details.
name: OZI

on:
  push:
    branches:
      - "v?[0-9].[0-9]*"
      - "v?[1-9]+[0-9].[0-9]*"

permissions:
  contents: read

jobs:


  checkpoint-cp311-ubuntu-latest:
    name: checkpoint (Python 3.11 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
        id-token: write
    steps:
      - uses: OZI-Project/checkpoint@f475dbf6078211f784f6e7b3bb7c1b00ce0d05b9
        with:
          python-version: "3.11"
  checkpoint-cp312-ubuntu-latest:
    name: checkpoint (Python 3.12 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
        id-token: write
    steps:
      - uses: OZI-Project/checkpoint@f475dbf6078211f784f6e7b3bb7c1b00ce0d05b9
        with:
          python-version: "3.12"
  checkpoint-cp313-ubuntu-latest:
    name: checkpoint (Python 3.13 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
        id-token: write
    steps:
      - uses: OZI-Project/checkpoint@f475dbf6078211f784f6e7b3bb7c1b00ce0d05b9
        with:
          python-version: "3.13"

  checkpoint:
    runs-on: ubuntu-latest
    needs: [checkpoint-cp311-ubuntu-latest,checkpoint-cp312-ubuntu-latest,checkpoint-cp313-ubuntu-latest,]
    steps:
      - run: echo "checkpoint success"


  draft:
    needs: checkpoint
    runs-on: ubuntu-latest
    concurrency: draft
    strategy:
      fail-fast: true
    permissions:
      contents: write
      id-token: write
    outputs:
      drafted: ${{ steps.draft.outputs.drafted }}
      tag: ${{ steps.draft.outputs.tag }}
    steps:
      - uses: OZI-Project/draft@cabcb89f38f90863aa0217f0b4b2dba02262b004
        id: draft


  release:
    needs: [draft, checkpoint]
    runs-on: ubuntu-latest
    concurrency: release
    strategy:
      matrix:
        py:
          - security2
          - security1
          - bugfix
          - prerelease
      fail-fast: true
      max-parallel: 1
    outputs:
      hashes: ${{ steps.release.outputs.hashes }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: OZI-Project/release@d3920f3f0471dec9369a2245cc6e6b42756d27f8
        id: release
        with:
          python-dist: ${{ matrix.py }}
          tag: ${{ needs.draft.outputs.tag }}


  provenance:
    needs: [draft, release]
    runs-on: ubuntu-latest
    name: Generate build provenance
    if: needs.draft.outputs.drafted == 'true'
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
    - uses: OZI-Project/provenance@a7369a6ef4a56f442b97615539b8de23dcb1e94e
      with:
        release-tag: ${{ needs.draft.outputs.tag }}


  publish:
    runs-on: ubuntu-latest
    needs: [draft, release, provenance]
    if: needs.draft.outputs.drafted == 'true'
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: OZI-Project/publish@ed9bff22f51f8b70c47a326e1e73a48174a8c6d2
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
      with:
        repository-url: "https://test.pypi.org/legacy/"